{
  "hash": "d4b22f6612c9b1713f7820f6b677563e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Frequency Distribution\"\nimage: \"/images/biostats.png\"\ndate: \"2024-10-05\"\nformat: \n  html: \n    fig-align: center\n    page-layout: article\n    code-fold: show\n    toc: true\n    toc-depth: 5\n    toc-expand: true\n    lightbox: false\ncrossref: \n  custom: \n    - kind: float\n      reference-prefix: \"Example M.10.\"\n      key: tabset\n      space-before-numbering: false\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n:::\n\n\n\n## Raw data\n\n-   It is defined as the original set of measurements or observations collected from a study or an experiment without being organized, summarized, or manipulated.\n\n## Ordered aray\n\n-   It is a set of data arranged in ascending or descending order.\n\n-   Example: Consider the following set of raw data (5, 3, 7, 2, 8, 4, 6, 1)\n\n    -   The ordered array of the data is (1, 2, 3, 4, 5, 6, 7, 8)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a vector of raw data\nraw_data <- c(5, 3, 7, 2, 8, 4, 6, 1)\n\n# sort the raw data in ascending order\nordered_array <- sort(raw_data)\n\n# display the ordered array\nordered_array\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 2 3 4 5 6 7 8\n```\n\n\n:::\n:::\n\n\n\n## Frequency distribution\n\n-   It is used to summarize raw data by grouping the data into classes and counting the number of observations in each class.\n\n### Categorical variables\n\n-   These variables can be summarized by counting the number of observations in each category (this count is known as the absolute frequency).\n\n-   The relative frequency of each category is the proportion of observations in that category relative to the total number of observations.\n\n-   Example: Consider the variable `vs` (engine type) in the `mtcars` dataset:\n\n    -   This variable contains two categories: `0` (V-shaped) and `1` (Straight).\n\n    -   The frequency distribution of the variable `vs` can be calculated using base R functions or directly using custom functions from `vtable` and `gtsummary` packages:\n\n::: panel-tabset\n## Base R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the mtcars dataset\ndata(mtcars)\n\n# display the values of the vs variable\nmtcars$vs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# check the type of the vs variable\nclass(mtcars$vs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# convert the variable to a factor\nmtcars$vs <-\n  factor(\n    mtcars$vs,\n    levels = c(0, 1),\n    labels = c(\"V-shaped\",\n               \"Straight\"\n             )\n  )\nlevels(mtcars$vs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"V-shaped\" \"Straight\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# create a frequency distribution table for the vs variable\nfreq_tbl <- table(mtcars$vs)\nfreq_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nV-shaped Straight \n      18       14 \n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate the relative frequency\nrel_freq <- prop.table(freq_tbl)\nrel_freq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nV-shaped Straight \n  0.5625   0.4375 \n```\n\n\n:::\n\n```{.r .cell-code}\n# display as percentage\nrbind(\n  names(rel_freq),\n  paste0(\n    round(\n      (rel_freq * 100), \n      digits = 1\n    ), \n    \"%\"\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     [,1]       [,2]      \n[1,] \"V-shaped\" \"Straight\"\n[2,] \"56.2%\"    \"43.8%\"   \n```\n\n\n:::\n:::\n\n\n\n## Using `sumtable()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vtable)\nlibrary(dplyr)\n\nmtcars %>%\n  select(vs) %>%  # select the vs variable\n  sumtable(\n    labels = 'Engine Type', # change the label of the vs variable\n    digits = 3, # set the number of digits \n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Summary Statistics</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:left;\"> N </th>\n   <th style=\"text-align:left;\"> Percent </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Engine Type </td>\n   <td style=\"text-align:left;\"> 32 </td>\n   <td style=\"text-align:left;\">  </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ... V-shaped </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:left;\"> 56.2% </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ... Straight </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:left;\"> 43.8% </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n## Using `tbl_summary()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nlibrary(dplyr)\n\nmtcars %>%\n  select(vs) %>%  # select the vs variable\n  tbl_summary(\n    label = list(vs = \"Engine Type\"),  # change the label of the vs variable\n    digits = vs ~ c(0, 1)  # set the number of digits, 0 for frequency and 1 for relative frequency\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gihisgowid\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gihisgowid table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gihisgowid thead, #gihisgowid tbody, #gihisgowid tfoot, #gihisgowid tr, #gihisgowid td, #gihisgowid th {\n  border-style: none;\n}\n\n#gihisgowid p {\n  margin: 0;\n  padding: 0;\n}\n\n#gihisgowid .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gihisgowid .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gihisgowid .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gihisgowid .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gihisgowid .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gihisgowid .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihisgowid .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gihisgowid .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gihisgowid .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gihisgowid .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gihisgowid .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gihisgowid .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gihisgowid .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gihisgowid .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gihisgowid .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gihisgowid .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gihisgowid .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gihisgowid .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gihisgowid .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihisgowid .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gihisgowid .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gihisgowid .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gihisgowid .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihisgowid .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gihisgowid .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gihisgowid .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihisgowid .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihisgowid .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gihisgowid .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihisgowid .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gihisgowid .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gihisgowid .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gihisgowid .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihisgowid .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gihisgowid .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gihisgowid .gt_left {\n  text-align: left;\n}\n\n#gihisgowid .gt_center {\n  text-align: center;\n}\n\n#gihisgowid .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gihisgowid .gt_font_normal {\n  font-weight: normal;\n}\n\n#gihisgowid .gt_font_bold {\n  font-weight: bold;\n}\n\n#gihisgowid .gt_font_italic {\n  font-style: italic;\n}\n\n#gihisgowid .gt_super {\n  font-size: 65%;\n}\n\n#gihisgowid .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gihisgowid .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gihisgowid .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gihisgowid .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gihisgowid .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gihisgowid .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gihisgowid .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gihisgowid .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gihisgowid div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipDaGFyYWN0ZXJpc3RpYyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Characteristic&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><div class='gt_from_md'><p><strong>Characteristic</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipOID0gMzIqKg==&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;N = 32&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><div data-qmd-base64=\"KipOID0gMzIqKg==\"><div class='gt_from_md'><p><strong>N = 32</strong></p>\n</div></div><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Engine Type</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    V-shaped</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">18 (56.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Straight</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">14 (43.8%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height: 0;\"><sup>1</sup></span> <div data-qmd-base64=\"biAoJSk=\"><div class='gt_from_md'><p>n (%)</p>\n</div></div></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n\n#### Graphical representation\n\n##### Bar chart\n\n-   This type of charts is used to represent the frequency distribution of categorical variables.\n\n-   It consists of a rectangular bar (column) for each category, where the height of the bar represents the absolute frequency or relative frequency of that category.\n\n-   The bars can be arranged horizontally or vertically.\n\n-   For ordinal scale variables, it is better to arrange the bars on the $x$-axis based on the order of the categories.\n\n-   The frequency distribution of the `vs` variable can be represented using a bar chart as follows:\n\n::: panel-tabset\n## Base R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a bar chart for the vs variable\nbarplot(\n  freq_tbl,\n  main = \"Frequency distribution of the Engine Type\",\n  xlab = \"Engine Type\",\n  ylab = \"Frequency\",\n  col = c(\"skyblue\", \"lightgreen\"),\n  border = \"black\",\n  names.arg = c(\"V-shaped\", \"Straight\"),\n  ylim = c(0, 20),\n  width = c(0.2,0.2), \n  xlim = c(0,1), \n  space = 1\n)\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n## Using `ggplot2`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\n\n# create a data frame from the frequency table\nfreq_tbl_df <-\n  data.frame(\n    engine_type =\n      factor(\n        names(freq_tbl), \n        levels = names(freq_tbl)\n      ),\n    freq = as.numeric(freq_tbl)\n  )\n\n# create a new column for the relative frequency\ntotal_freq <- sum(freq_tbl)\n\nfreq_tbl_df <-\n  freq_tbl_df %>%\n  mutate(\n    rel_freq =\n      round(\n        (freq / total_freq) * 100,\n        digits = 1\n      )\n  )\n\n# create a bar chart with frequency on y-axis\nfig1 <- \n  ggplot(\n  freq_tbl_df,\n  aes(\n    x = engine_type,\n    y = freq,\n    fill = engine_type\n  )\n) +\n  geom_col(width = 0.5) + # you can also use geom_bar(stat = \"identity\")\n  labs(\n    title = \"Frequency distribution \\n of the Engine Type\",\n    x = \"Engine Type\",\n    y = \"Frequency\"\n  ) +\n  scale_fill_manual(\n    values = c(\"skyblue\", \"lightgreen\")\n  ) +\n  scale_y_continuous(\n    limits = c(0,20),\n    expand = c(0, 0),\n  ) +\n  theme_bw() +\n  theme(\n    axis.text.x = element_blank(), \n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5)\n  )\n\n# create a bar chart with relative frequency on y-axis\nfig2 <- \n  ggplot(\n  freq_tbl_df,\n  aes(\n    x = engine_type,\n    y = rel_freq,\n    fill = engine_type\n  )\n) +\n  geom_col(width = 0.5) + \n  labs(\n    title = \"Relative Frequency \\n distribution of the Engine Type\",\n    x = \"Engine Type\",\n    y = \"Relative Frequency (%)\", \n    fill = \"Engine Type\"\n  ) +\n  scale_fill_manual(\n    values = c(\"skyblue\", \"lightgreen\")\n  ) +\n  scale_y_continuous(\n    limits = c(0,60),\n    expand = c(0, 0),\n  ) +\n  theme_bw() +\n  theme(\n    axis.text.x = element_blank(),\n    plot.title = element_text(hjust = 0.5)\n  )\n\nfig1 + plot_spacer() + fig2 + plot_layout(widths = c(1, 0.05, 1))\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n## Horizontal bar chart\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use the same code as described in the previous tab but just add coord_flip() to the ggplot object\n\n\nggplot(\n  freq_tbl_df,\n  aes(\n    x = engine_type,\n    y = rel_freq,\n    fill = engine_type\n  )\n) +\n  geom_col(width = 0.5) + \n  labs(\n    title = \"Relative Frequency distribution of the Engine Type\",\n    x = \"Engine Type\",\n    y = \"Relative Frequency (%)\", \n    fill = \"Engine Type\"\n  ) +\n  scale_fill_manual(\n    values = c(\"skyblue\", \"lightgreen\")\n  ) +\n  scale_y_continuous(\n    limits = c(0,60),\n    expand = c(0, 0),\n  ) +\n  coord_flip() +\n  theme_bw() +\n  theme(\n    axis.text.y = element_blank(), \n  )\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n:::\n\n##### Pie chart\n\n-   It is also used to represent the frequency distribution of categorical variables.\n\n-   It consists of a circle divided into parts, where each part represents a category.\n\n-   The size of each part is equal to the angle, which is calculated by multiplying the relative frequency of the category by $360 ^\\circ$ (the total angle of a circle).\n\n-   For instance, the relative frequency of the V-shaped engine in the above example is $\\displaystyle \\frac{18}{32} = 0.5625$, this corresponds to an angle of $\\displaystyle 0.5625 \\times 360 = 202.5^\\circ$ degrees.\n\n-   The pie chart is suitable for variables with a small number of categories; it becomes cluttered and hard to read when the number of categories is large.\n\n::: panel-tabset\n## Base R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extract the relative frequencies from the data frame created above\npercentages <- freq_tbl_df$rel_freq\n\n# create labels with the percentages\nlabels <- \n    paste0(c(\"V-shaped\", \"Straight\"), \n           \"\\n\", \n           percentages, \n           \"%\"\n   )\n\n# create a pie chart \npie(\n  freq_tbl,\n  main = \"Pie chart of the Engine Type\",\n  col = c(\"skyblue\", \"lightgreen\"),\n  labels = labels,  # Use the percentage labels\n  clockwise = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n## Using `ggplot2`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(\n  freq_tbl_df,\n  aes(\n    x = \"\",\n    y = rel_freq,\n    fill = engine_type\n  )\n) +\n  geom_bar(\n    stat = \"identity\",\n    width = 1\n  ) +\n  coord_polar(\"y\", start = 0) +\n  labs(\n    title = \"Pie chart of the Engine Type\",\n    fill = \"Engine Type\"\n  ) +\n  scale_fill_manual(\n    values = c(\"skyblue\", \"lightgreen\")\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"none\", \n    plot.title = element_text(hjust = 0.5)\n  ) +\n  geom_text(\n    aes(label = labels),\n    position = position_stack(vjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n:::\n\n### Numerical data\n\n-   Continuous numerical variables have many unique values, which can lead to an extremely large number of categories.\n\n-   Therefore, these variables can be summarized by grouping the data into class intervals and counting the number of observations in each class interval.\n\n-   The class intervals are selected to be contiguous, non-overlapping, and exhaustive in a way that each observation can be assigned to one and only one class interval.\n\n-   Constructing few class intervals may result in loss of information, while constructing too many class intervals may not satisfy the purpose of summarizing the data.\n\n-   A rule of thumb is to have between 5 and 15 class intervals.\n\n-   There are different methods used as a guide to determine the number of class intervals, such as Sturges' rule, square root method, Freedman-Diaconis' rule, etc, for example:\n\n    -   **Sturges' rule**: $k = 1 + 3.322 \\log_{10}(n)$, where $k$ is the number of class intervals and $n$ is the number of observations.\n\n-   Example: Consider the variable `mpg` (miles per gallon) in the `mtcars` dataset.\n\n    -   The number of class intervals based on Sturges' rule can be calculated as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the mtcars dataset\ndata(mtcars)\n\n# display the values of the mpg variable\nmtcars$mpg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4\n[16] 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7\n[31] 15.0 21.4\n```\n\n\n:::\n:::\n\n\n\n::: panel-tabset\n## Stepwise calculation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# determine the number of observations\nn <- length(mtcars$mpg)\n\n# calculate the number of class intervals using Sturges' rule\nk <- 1 + 3.322 * log10(n)\nk\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.000108\n```\n\n\n:::\n:::\n\n\n\n## Direct calculation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use nclass.Sturges() function \nnclass.Sturges(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# determine the minimum value of the mpg variable\nmin_mpg <- min(mtcars$mpg)\n\n# determine the maximum value of the mpg variable\nmax_mpg <- max(mtcars$mpg)\n\n# calculate the range of the mpg variable by subtracting the minimum from the maximum\nr <- max_mpg - min_mpg\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.5\n```\n\n\n:::\n:::\n\n\n\n-   The number of class intervals is 6 as suggested by Sturges' rule.\n\n::: {.callout-note style=\"color: #0466c8;\"}\n-   These rules including Sturges' rule are not strict but rather provide guidance to determine the number of class intervals.\n\n-   The actual number of class intervals can vary based on the researcher's judgment and the purpose of the analysis.\n:::\n\n-   The width of each class interval is approximately equal to $\\displaystyle \\frac {\\text{Range}}{k} = \\frac{23.5}{6} = 3.9 \\approx 4$.\n\n-   As a rule of thumb, when appropriate, the width of the class interval is recommended to be of of 5 units, 10 units, or multiples of 10.\n\n-   The first class interval should encompass the minimum $(10.4)$, while the last class interval should encompass the maximum $(33.9)$.\n\n-   A good starting point would be $10$ and considering a width of $5$ units, the boundaries of the class intervals would be $10, 15, 20, 25, 30, \\text {and}\\ 35$.\n\n-   Because each value should be assigned to one and only one class interval, the class intervals should be closed on one end and open on the other end, e.g., $[10, 15], (15, 20], (20, 25], (25, 30], (30, 35]$.\n\n::: {.callout-note style=\"color: #0466c8;\"}\n-   The square bracket \\[ \\] denotes that the interval includes the corresponding lower or upper bound, while the parenthesis ( ) denotes that the interval excludes the corresponding lower or upper bound.\n\n-   For instance, the second class interval $(15, 20]$ includes values greater than but not equal to $15$ and less than or equal to $20$ (i.e., $15 < x \\leq 20$).\n\n-   This type is called exclusive-inclusive (also known as half-open, half-closed) intervals.\n\n-   The first class interval should have a closed lower bound to include the minimum value, if coincidentally the minimum value is equal to the lower bound of the first class interval.\n:::\n\n-   The class interval boundaries (i.e., breakpoints) can also be determined directly using the `pretty()` function in R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npretty(mtcars$mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10 15 20 25 30 35\n```\n\n\n:::\n\n```{.r .cell-code}\n# change the number of class intervals using n argument\npretty(mtcars$mpg, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10 20 30 40\n```\n\n\n:::\n:::\n\n\n\n-   We can use R to create a frequency distribution table for the `mpg` variable as follows:\n\n\n\n::: {#tbl-mpg-freq .cell tbl-cap='Frequency distribution of the mpg variable'}\n\n```{.r .cell-code}\nlibrary(DT)\n\n# create a vector to assign each value to a class interval\nmpg_class <-\n  cut(\n    mtcars$mpg,\n    breaks = seq(10, 35, by = 5),\n    include.lowest = TRUE,\n    right = TRUE\n  )\n\n# include.lowest = TRUE ensures that the minimum value is included in the first class interval or the maximum value is included in the last class interval if right argument is set to FALSE.\n\n# right = TRUE ensures that the intervals are left-open and right-closed.\n\n# create a frequency distribution table for the mpg variable\nfreq_tbl_1 <- table(mpg_class)\n\n# create a data frame from the frequency table\nfreq_tbl_df_1 <- data.frame(freq_tbl_1)\nfreq_tbl_df_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mpg_class Freq\n1   [10,15]    6\n2   (15,20]   12\n3   (20,25]    8\n4   (25,30]    2\n5   (30,35]    4\n```\n\n\n:::\n\n```{.r .cell-code}\n# convert the mpg_class column to character\nfreq_tbl_df_1$mpg_class <- as.character(freq_tbl_df_1$mpg_class)\n\n# add a row for the total frequency\nfreq_tbl_df_1 <-\n  rbind(\n    freq_tbl_df_1, \n    c(\"Total\", \n      sum(freq_tbl_df_1$Freq)\n     )\n  )\n\n# display the frequency distribution table (optional)\ndatatable(\n  freq_tbl_df_1,\n  colnames = c(\n    \"Class Interval\" = \"mpg_class\",\n    \"Frequency\" = \"Freq\"\n  ),\n  options = list(\n    dom = \"t\",\n    columnDefs = list(\n      list(\n        className = \"dt-center\",\n        targets = \"_all\"\n      )\n    )\n  ),\n  rownames = FALSE\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-f071e5cc68c9307cf2f1\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f071e5cc68c9307cf2f1\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"[10,15]\",\"(15,20]\",\"(20,25]\",\"(25,30]\",\"(30,35]\",\"Total\"],[\"6\",\"12\",\"8\",\"2\",\"4\",\"32\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Class Interval<\\/th>\\n      <th>Frequency<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"columnDefs\":[{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"mpg_class\",\"targets\":0},{\"name\":\"Freq\",\"targets\":1}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### Relative and cumulative frequencies\n\n-   Relative frequency of a class interval:\n\n    -   It is the proportion of observations that fall within that class interval relative to the total number of observations.\n\n    -   It is simply calculated by dividing the frequency of that class interval by the total number of observations.\n\n-   Cumulative frequency:\n\n    -   As the name implies, it is the frequency of values falling within two or more class intervals.\n\n    -   At each class interval, we calculate the sum of the frequency of that class interval and all previous class intervals.\n\n-   Cumulative relative frequency:\n\n    -   It is calculated by dividing the cumulative frequency by the total number of observations.\n\n::: {.callout-note style=\"color: #0466c8;\"}\n-   The relative frequency, cumulative frequency, and cumulative relative frequency are calculated for categorical variables in the same way as for numerical variables.\n:::\n\n-   The relative frequency, cumulative frequency, and cumulative relative frequency of the `mpg` variable can be calculated as follows:\n\n\n\n::: {#tbl-mpg-cum-freq .cell tbl-cap='Cumulative frequency distribution of the mpg variable'}\n\n```{.r .cell-code}\n# calculate the relative frequency\nrel_freq_1 <- prop.table(freq_tbl_1)\nrel_freq_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmpg_class\n[10,15] (15,20] (20,25] (25,30] (30,35] \n 0.1875  0.3750  0.2500  0.0625  0.1250 \n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate the cumulative frequency\ncum_freq_1 <- cumsum(freq_tbl_1)\ncum_freq_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[10,15] (15,20] (20,25] (25,30] (30,35] \n      6      18      26      28      32 \n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate the cumulative relative frequency\ncum_rel_freq_1 <- cumsum(rel_freq_1)\ncum_rel_freq_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[10,15] (15,20] (20,25] (25,30] (30,35] \n 0.1875  0.5625  0.8125  0.8750  1.0000 \n```\n\n\n:::\n\n```{.r .cell-code}\n# create a data frame from the cumulative frequency table\ncum_freq_df_1 <-\n  data.frame(\n    freq_tbl_1,\n    cum_freq_1 = as.numeric(cum_freq_1),\n    rel_freq_1 = as.numeric(rel_freq_1),\n    cum_rel_freq_1 = as.numeric(cum_rel_freq_1)\n  )\n\n# convert the mpg_class column to character\ncum_freq_df_1$mpg_class <- as.character(cum_freq_df_1$mpg_class)\n\n# add a row for the total frequency\ncum_freq_df_1 <-\n  rbind(\n    cum_freq_df_1,\n    c(\n      \"Total\",\n      sum(cum_freq_df_1$Freq),\n      NA,\n      sum(cum_freq_df_1$rel_freq),\n      NA\n    )\n  )\n\n\n# display the cumulative frequency distribution table\ndatatable(\n  cum_freq_df_1,\n  colnames = c(\n    \"Class Interval\" = \"mpg_class\",\n    \"Frequency\" = \"Freq\",\n    \"Cumulative Frequency\" = \"cum_freq_1\",\n    \"Relative Frequency\" = \"rel_freq_1\",\n    \"Cumulative Relative Frequency\" = \"cum_rel_freq_1\"\n  ),\n  options = list(\n    dom = \"t\",\n    columnDefs = list(\n      list(\n        className = \"dt-center\", \n        targets = \"_all\"\n      )\n    )\n  ),\n  rownames = FALSE\n) %>%\n  formatRound(\n  columns = c(4, 5),\n  digits = 5\n) %>%\n  formatStyle(\n    columns = c(1:5),\n    backgroundColor = styleRow(\n      3,\n      \"lightgreen\"\n    ) \n  ) %>%\n  formatStyle(\n    columns = c(4:5),\n    backgroundColor = styleEqual(\n      1,\n      c(\"skyblue\")\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-f99e74ac721039b3695f\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f99e74ac721039b3695f\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"[10,15]\",\"(15,20]\",\"(20,25]\",\"(25,30]\",\"(30,35]\",\"Total\"],[\"6\",\"12\",\"8\",\"2\",\"4\",\"32\"],[\"6\",\"18\",\"26\",\"28\",\"32\",null],[\"0.1875\",\"0.375\",\"0.25\",\"0.0625\",\"0.125\",\"1\"],[\"0.1875\",\"0.5625\",\"0.8125\",\"0.875\",\"1\",null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Class Interval<\\/th>\\n      <th>Frequency<\\/th>\\n      <th>Cumulative Frequency<\\/th>\\n      <th>Relative Frequency<\\/th>\\n      <th>Cumulative Relative Frequency<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"columnDefs\":[{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 5, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 5, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-center\",\"targets\":\"_all\"},{\"name\":\"mpg_class\",\"targets\":0},{\"name\":\"Freq\",\"targets\":1},{\"name\":\"cum_freq_1\",\"targets\":2},{\"name\":\"rel_freq_1\",\"targets\":3},{\"name\":\"cum_rel_freq_1\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"rowCallback\":\"function(row, data, displayNum, displayIndex, dataIndex) {\\nvar value=data[0]; $(this.api().cell(row, 0).node()).css({'background-color':$.inArray(dataIndex + 1, [3]) >= 0 ? \\\"lightgreen\\\" : null});\\nvar value=data[1]; $(this.api().cell(row, 1).node()).css({'background-color':$.inArray(dataIndex + 1, [3]) >= 0 ? \\\"lightgreen\\\" : null});\\nvar value=data[2]; $(this.api().cell(row, 2).node()).css({'background-color':$.inArray(dataIndex + 1, [3]) >= 0 ? \\\"lightgreen\\\" : null});\\nvar value=data[3]; $(this.api().cell(row, 3).node()).css({'background-color':$.inArray(dataIndex + 1, [3]) >= 0 ? \\\"lightgreen\\\" : null});\\nvar value=data[4]; $(this.api().cell(row, 4).node()).css({'background-color':$.inArray(dataIndex + 1, [3]) >= 0 ? \\\"lightgreen\\\" : null});\\nvar value=data[3]; $(this.api().cell(row, 3).node()).css({'background-color':value == 1 ? \\\"skyblue\\\" : null});\\nvar value=data[4]; $(this.api().cell(row, 4).node()).css({'background-color':value == 1 ? \\\"skyblue\\\" : null});\\n}\"}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.rowCallback\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n-   As you can see from @tbl-mpg-cum-freq:\n\n    -   The relative frequency of the class interval $(20, 25] = \\displaystyle \\frac{8}{32} = 0.25$.\n\n    -   The cumulative frequency at the class interval $(20, 25] = 6 + 12 + 8 = 26$, which represents the number of observations that fall within the wider class interval $[10, 25]$ that incorporates the class intervals $[10, 15]$, $(15, 20]$, and $(20, 25]$.\n\n    -   The cumulative relative frequency at the class interval $(20, 25] = \\displaystyle \\frac{6}{32} + \\frac{12}{32} + \\frac{8}{32} = \\frac{26}{32} = 0.8125$.\n\n    -   Notice:\n\n        -   The relative frequncies should sum up to 1.\n\n        -   The cumulative relative frequency at the last class interval should be 1.\n\n#### Graphical representation\n\n##### Histogram\n\n-   It is used to graphically represent the distribution of values of continuous variables.\n\n-   It can be used to get insights about the underlying shape of the distribution that generated the data based on the sample.\n\n-   The class intervals are represented by the horizontal axis, whereas the vertical axis represents the frequency of the values or the relative frequency `density` scale.\n\n-   Each class interval on the horizontal axis has a rectangular vertical bar.\n\n-   If the vertical axis scale is the `frequency`, the height $(h_i)$ of the bar corresponds to the frequency $(n_i)$ of that class interval (i.e., $h_i = n_i$).\n\n-   If the vertical axis scale is the `density`, the height of the bar corresponds to relative frequency $\\left ( f_i = \\displaystyle \\frac{n_i}{\\sum n_i} \\right)$ of that class interval divided by the width $(d_i)$ of the class interval (i.e., $h_i = \\displaystyle \\frac{f_i}{d_i}$):\n\n    -   Therefore, the area of each bar $= \\text {height} \\times \\text {width} = \\displaystyle \\frac{f_i}{\\cancel{d_i}} \\times \\cancel{d}_i = f_i$ (i.e., the relative frequency).\n\n    -   In this context, the widths of the bars can have different widths because the area of each bar is proportional to the relative frequency (however, usually the bars have equal width).\n\n-   The bars are contiguous, non-overlapping, and possess no gaps.\n\n-   The histogram of the `mpg` variable can be created as follows:\n\n::: panel-tabset\n## Base R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adjust the plot layout to display two plots side by side\npar(mfrow=c(1,2))\n\n# create a histogram based on frequency\nhist(\n  x = mtcars$mpg,\n  main = \"Histogram based \\n on frequency\",\n  xlab = \"Miles per Gallon (MPG)\",\n  ylab = \"Frequency\",\n  col = \"skyblue\",\n  border = \"black\",\n  ylim = c(0, 14),\n)\n\n# The breaks were determined automatically but it can be changed using the breaks  argument\n\n# hist() uses left-open and right-closed intervals by default.\n\n\n# create a histogram based on relative frequency\nhist(\n  mtcars$mpg,\n  prob = TRUE, # this is equivalent tp freq = FALSE\n  main = \"Histogram based on \\n relative frequency\",\n  xlab = \"Miles per Gallon (MPG)\",\n  ylab = \"Density\",\n  col = \"skyblue\",\n  border = \"black\",\n  ylim = c(0, 0.08),\n)\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n## Using `ggplot2`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# create a histogram based on frequency\n\nh1 <- \nggplot(mtcars, aes(x = mpg)) + # aes() needs x argument only\n  geom_histogram(\n    fill = \"skyblue\",\n    color = \"black\"\n  ) +\n  labs(\n    title = \"Histogram based on frequency\",\n    x = \"Miles per Gallon (MPG)\",\n    y = \"Frequency\"\n  ) +\n  theme_bw()\n\nh1\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n-   The histogram is different from the base R histogram because `ggplot()` uses 30 bins (bars) by default, which might not be appropriate all the time.\n\n-   This can be changed by using the `bins` argument in `geom_histogram()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh2 <-\n  ggplot(mtcars, aes(x = mpg)) + \n  geom_histogram(\n    fill = \"skyblue\",\n    color = \"black\",\n    bins = 5\n  ) +\n  labs(\n    title = \"Histogram based on frequency\",\n    x = \"Miles per Gallon (MPG)\",\n    y = \"Frequency\"\n  ) +\n  theme_bw()\n\nh2\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n-   Now, we have 5 bins like the histogram created by base R, however, the ticks on the $x$-axis and bin width are different.\n\n-   We can check the breaks created by `ggplot()` using the following code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot_build(h2)$data[[1]]$xmin\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  8.8125 14.6875 20.5625 26.4375 32.3125\n```\n\n\n:::\n:::\n\n\n\n-   To get the same breaks as in the base R histogram, we can adjust the arguments `binwidth`, `boundary`, and `closed` in the `geom_histogram()` as follows\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh3 <-\n  ggplot(mtcars, aes(x = mpg)) + \n  geom_histogram(\n    fill = \"skyblue\",\n    color = \"black\", \n    binwidth = 5, \n    boundary = 0,\n    closed = \"right\"\n  ) +\n  labs(\n    title = \"Histogram based on frequency\",\n    x = \"Miles per Gallon (MPG)\",\n    y = \"Frequency\"\n  ) +\n  scale_y_continuous(\n    breaks = seq(0, 14, by = 2),\n    limits = c(0, 14),\n    expand = c(0, 0)\n  ) +\n  theme_bw() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\nh3\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n-   The histogram based on relative frequency can be created as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# histogram based on relative frequency using after_stat(density) as argument insides aes() \nh4 <-\n  ggplot(mtcars, aes(x = mpg, after_stat(density))) + \n  geom_histogram(\n    fill = \"skyblue\",\n    color = \"black\", \n    binwidth = 5, \n    boundary = 0, \n    closed = \"right\", \n  ) +\n  labs(\n    title = \"Histogram based on \\n relative frequency\",\n    x = \"Miles per Gallon (MPG)\",\n    y = \"Desnsity\"\n  ) +\n  scale_y_continuous(\n    limits = c(0, 0.08),\n    expand = c(0, 0)\n  ) +\n  theme_bw() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n  \nh4\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n-   Display both histograms side by side:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\nh3 + h4\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n:::\n\n##### Kernel density plot\n\n-   The histogram has a disadvantage in that the shape of the distribution is influenced by the choice of the number of class intervals (i.e., bins). Different bin sizes can give a different impression of the underlying distribution.\n\n-   This problem can be addressed by using the kernel density plot, which is a smoothed version of the histogram and less sensitive to the choice of the number of bins.\n\n-   Using the kernel density plot, the shape of the distribution is represented by a continuous function (i.e., curve) estimated from the sample data.\n\n-   Like histograms, the density plots give insights about the underlying shape of the distribution that generated the data based on the sample.\n\n-   In simple words, the kernel density estimation (KDE) is based on the idea that the more data points are clustered together, the higher is the probability density in that region (i.e., the higher is the probability of an observation falling in that region):\n\n    -   KDE places a small kernel (bump) centered at each data point.\n\n    -   The density of the bump is highest at the data points and decreases by moving move away from the data points.\n\n    -   The small kernels (bumps) are summed to estimate the overall density at each point.\n\n-   Assume the following set of data: $5, 6, 7, 8, 11, 12$:\n\n\n\n    ::: {.cell}\n    ::: {.cell-output-display}\n    ![](001_desc_stats_files/figure-html/unnamed-chunk-25-1.png){width=672}\n    :::\n    :::\n\n\n\n    -   In the above density plot:\n\n        -   The dashed lines represent the small bumps (kernel functions) centered at each data point.\n\n        -   The solid red line represents the overall kernel density estimate.\n\n        -   The green tickmarks at the bottom of the plot represent the data points.\n\n    -   The small bumps are summed to estimate the overall density.\n\n    -   The overall desnsity is highest between 5 and 8 because more data points are clustered in that region.\n\n-   The kernel function used for the estimation is given by:\n\n$$\n\\displaystyle \\hat f_n(x) = \\frac{1}{nh} \\sum_{i=1}^{n} K \\left( \\frac{x - x_i}{h} \\right)\n$$\n\n::: {style=\"margin-left: 50px; color: #0466c8;\"}\n-   $\\hat f_n(x)$ is the kernel density estimate at $x$\n\n-   $n$ is the number of observations\n\n-   $h$ is the bandwidth and $h > 0$\n\n-   $\\displaystyle K \\left( \\frac{x - x_i}{h} \\right)$ is the kernel function (mentioned below as $K(u)$, where $u = \\displaystyle \\frac{x - x_i}{h}$)\n\n-   $x_i$ is the $i^{\\text{th}}$ observation of the data\n:::\n\n-   There are different kernel functions, such as the Gaussian kernel, Epanechnikov kernel, rectangular kernel, etc:\n\n    | Kernel Function | Formula |\n    |------------------------------------|:----------------------------------:|\n    | Gaussian (default in R) | $$\n    K(u) = \\displaystyle \\frac{1}{\\sqrt{2\\pi}} e^{-\\large \\frac{u^2}{2}}\n    $$ |\n    | Epanechnikov | $$\n        K(u) =\n        \\begin{cases} \n        \\displaystyle \\frac{3}{4}(1 - u^2) &  \\quad \\text{if}\\ |u| \\lt 1 \\\\ \\\\\n        0 & \\quad \\text{otherwise}\n        \\end{cases}\n    $$ |\n    | Rectangular | $$\n        K(u) =\n        \\begin{cases} \n        \\displaystyle \\frac{1}{2} &  \\quad \\text{if}\\ -1 \\le u \\le 1 \\\\ \\\\\n        0 & \\quad \\text{otherwise}\n        \\end{cases}\n    $$ |\n\n-   Characteristics of the kernel function:\n\n    -   The kernel function is symmetric around zero.\n\n    -   The kernel function integrates to one (this makes the kernel density estimator a probability density function, a concept tha will be discussed in upcoming tutorials).\n\n-   The kernel density plot can be created in R as follows (for the `mpg` variable):\n\n::: panel-tabset\n## Base R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a kernel density plot using the default Gaussian kernel\nplot(\n  density(\n    mtcars$mpg\n  ),\n  main = \"Kernel density plot\",\n  xlab = \"Miles per Gallon (MPG)\",\n  ylab = \"Density\",\n  col = \"#0466c8\",\n  lwd = 2, \n  ylim = c(0, 0.08)\n)\n\n# add a kernel density plot using the Epanechnikov kernel\nlines(\n  density(\n    mtcars$mpg,\n    kernel = \"epanechnikov\",\n  ),\n  col = \"#e63946\",\n  lty = \"dashed\", \n  lwd = 1.5\n)\n\n# add a legend\nlegend(\n  \"topleft\",\n  legend = c(\"Gaussian\", \"Epanechnikov\"),\n  col = c(\"#0466c8\", \"#e63946\"),\n  lty = c(\"solid\", \"dashed\"),\n  lwd = c(2, 1.5)\n)\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n## Using `ggplot2`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n# create a kernel density plot using the default Gaussian kernel\nggplot(data = mtcars, aes(x = mpg)) +  # ggplot() accepts only a data frame\n  stat_density(\n    aes(color = \"Gaussian\"),  # Label used in the legend \n    kernel = \"gaussian\",  # default kernel\n    geom = \"line\",\n  ) +\n  stat_density(\n    aes(color = \"Epanechnikov\"),  # Label used in the legend\n    kernel = \"epanechnikov\",\n    linetype = \"dashed\",\n    geom = \"line\",\n  ) + \n  labs(\n    title = \"Kernel density plot\",\n    x = \"Miles per Gallon (MPG)\",\n    y = \"Density\", \n    color = \"Kernel\"  # title of legend\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Gaussian\" = \"#0466c8\", \n      \"Epanechnikov\" = \"#ba181b\"\n    ) \n  ) +\n  xlim(2, 40) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n:::\n\n-   The shape of kernel density plot is affected by the choice of the $h$ `(bandwidth)` parameter, which controls the smoothness of the curve:\n\n    -   When $h$ is too small, the curve becomes wiggly (i.e., undersmoothed) because the bandwidth is too narrow to smooth out random fluctuations in the data (i.e., the density estimate captures noise rather than the true underlying distribution).\n\n    -   When $h$ is too large, the curve becomes oversmoothed because the wide bandwidth smooths out (i.e., combines) more bumps leading to a density estimate that fails to capture the true underlying distribution.\n\n    -   The bandwidth can be controlled using the `bw` argument in both `density()` and `stat_density()` functions.\n\n    -   This can be illustrated by the following figure:\n\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    # plot density with default bandwidth \n    plot(\n      density(\n    mtcars$mpg\n      ),\n      main = \"Kernel density plot with different bandwidths\",\n      xlab = \"Miles per Gallon (MPG)\",\n      ylab = \"Density\",\n      col = \"#0466c8\",\n      lwd = 2, \n      ylim = c(0, 0.1)\n    )\n    \n    # add a kernel density plot with a smaller bandwidth\n    lines(\n      density(\n    mtcars$mpg,\n     bw = 1\n      ),\n      col = \"#e63946\",\n      lwd = 2\n    )\n    \n    # add a kernel density plot with a larger bandwidth\n    lines(\n      density(\n    mtcars$mpg,\n    bw = 6\n      ),\n      col = \"#38b000\",\n      lwd = 2\n    )\n    \n    # add a legend\n    legend(\n      \"topleft\",\n      legend = c(\"h=default\", \"h=0.5\", \"h=3\"),\n      col = c(\"#0466c8\", \"#e63946\", \"#38b000\"),\n      lwd = c(2, 2, 2)\n    )\n    ```\n    \n    ::: {.cell-output-display}\n    ![](001_desc_stats_files/figure-html/unnamed-chunk-28-1.png){width=672}\n    :::\n    :::\n\n\n\n::: {.callout-note style=\"color: #0466c8;\"}\n-   R uses its own algorithm to estimate the density, the following is quoted from the `density()` function documentation:\n\n    -   \"The algorithm used in density.default disperses the mass of the empirical distribution function over a regular grid of at least 512 points and then uses the fast Fourier transform to convolve this approximation with a discretized version of the kernel and then uses linear approximation to evaluate the density at the specified points.\n\n    -   By default, R calculates the bandwidth using Silverman's rule of thumb:\n\n        -   $\\displaystyle h = 0.9 \\times \\text{min} \\left( \\hat \\sigma, \\frac{\\text{IQR}}{1.34} \\right) \\times n^{-\\large \\frac{1}{5}}$\n\n        -   where $\\hat \\sigma$ is the standard deviation estimated from the sample, $\\text{IQR}$ is the interquartile range of, and $n$ is the number of observations.\n        \n        -   The bandwidth `(bw)` is then multiplied by `adjust` (default is 1) to get the final bandwidth.\n        \n        -   Therefore, modifying the `adjust` argument can change the bandwidth, e.g., if `adjust` is set to 0.5, the bandwidth is halved.\n        \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](001_desc_stats_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n## References\n\n-   Chen, Y. (2017). Lecture 7: Density Estimation. University of Washington. Retrieved October 05, 2024, from https://faculty.washington.edu/yenchic/17Sp_403/Lec7-density.pdf\n\n-   Daniel, W. W. and Cross, C. L. (2013). Biostatistics: A Foundation for Analysis\nin the Health Sciences, Tenth edition. Wiley\n\n-   Heumann, C., Schomaker, M., and Shalabh (2022). Introduction to Statistics and Data Analysis: With Exercises, Solutions and Applications in R. Springer\n\n-   Lane, D. M. et al., (2019). Introduction to Statistics. Online Edition. Retrieved September 14, 2024, from https://openstax.org/details/introduction-statistics\n\n\n<br>\n\n## Add your comments",
    "supporting": [
      "001_desc_stats_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}